import type { Product } from "@/features/products/types/product.types";

const defaultVolumeOption = {
  id: "volume",
  name: "Select Volume",
  values: ["30 ml", "50 ml", "100 ml"],
};

export const mockProducts: Product[] = [
  {
    id: "fleur-de-lune",
    name: "Fleur de Lune",
    description: "A luminous floral composition of jasmine and white musk.",
    notes: "Floral / Jasmine & White Musk",
    price: 195,
    images: ["/images/products/fleur-de-lune.png"],
    category: "pure-extractions",
    scentFamily: "floral",
    occasion: "personal-use",
    options: [defaultVolumeOption],
    topNotes: "White Neroli, Crisp Pear",
    heartNotes: "Night-Blooming Jasmine, Lily of the Valley",
    baseNotes: "White Musk, Sheer Cedar",
    inStock: true,
  },
  {
    id: "santal-parchment",
    name: "Santal Parchment",
    description:
      "Santal Parchment wraps around the skin like vintage vellum paper. It opens with bright top notes, shifting to clean papyrus and warm, rich sandalwood that dry down into dry cardamom and amber.",
    notes: "Woody / Sandalwood & Cardamom",
    price: 220,
    images: ["/images/products/santal-parchment.png"],
    category: "pure-extractions",
    scentFamily: "woody",
    occasion: "evening",
    options: [defaultVolumeOption],
    topNotes: "Sicilian Bergamot, Pink Pepper",
    heartNotes: "Egyptian Jasmine Sambac, Papyrus",
    baseNotes: "West Indian Sandalwood, Cardamom, Amber",
    inStock: true,
  },
  {
    id: "noir-cocoon",
    name: "Noir Cocoon",
    description: "An oriental blend of tobacco and amber.",
    notes: "Oriental / Tobacco & Amber",
    price: 240,
    images: ["/images/products/noir-cocoon.png"],
    category: "private-reserve",
    scentFamily: "oriental",
    occasion: "wedding",
    options: [defaultVolumeOption],
    topNotes: "Black Pepper, Bitter Orange",
    heartNotes: "Smoked Tobacco Leaf, Tonka Bean",
    baseNotes: "Golden Amber, Madagascar Vanilla",
    inStock: true,
  },
  {
    id: "sol-dor",
    name: "Sol d'Or",
    description: "A fresh coastal blend of bergamot and sea salt.",
    notes: "Fresh / Bergamot & Sea Salt",
    price: 185,
    images: ["/images/products/sol-dor.png"],
    category: "pure-extractions",
    scentFamily: "fresh",
    occasion: "personal-use",
    options: [defaultVolumeOption],
    topNotes: "Calabrian Bergamot, Sea Breeze",
    heartNotes: "Marine Accord, Orange Blossom",
    baseNotes: "Sun-Drenched Driftwood, Musk",
    inStock: true,
  },
  {
    id: "atelier-oud",
    name: "Atelier Oud",
    description: "Rich oud deepened with saffron.",
    notes: "Woody / Rich Oud & Saffron",
    price: 310,
    images: ["/images/products/atelier-oud.png"],
    category: "atelier-oils",
    scentFamily: "woody",
    occasion: "gift-sets",
    options: [defaultVolumeOption],
    topNotes: "Saffron Threads, Nutmeg",
    heartNotes: "Smoked Agarwood, Rose Petals",
    baseNotes: "Precious Oud, Leather, Benzoin",
    inStock: true,
  },
  {
    id: "rose-absolute",
    name: "Rose Absolute",
    description: "Damask rose balanced with cedar.",
    notes: "Floral / Damask Rose & Cedar",
    price: 205,
    images: ["/images/products/rose-absolute.png"],
    category: "private-reserve",
    scentFamily: "floral",
    occasion: "birthday",
    options: [defaultVolumeOption],
    topNotes: "Sparkling Mandarin, Morning Dew",
    heartNotes: "Turkish Damask Rose, Peony",
    baseNotes: "Atlas Cedarwood, Soft Patchouli",
    inStock: true,
  },
];
